### ISSUE TITLE
Plugin doesn't load on mobile app

### ISSUE THREAD

**Issue by safrilth** [xRyul/obsidian-image-converter#1]
plugin doesn't load on my android app (v.1.4.6).. 

i hope it will be fixed soon..

thankyou for building this amazing plugin..

**Comment by xRyul** [comment]
> plugin doesn't load on my android app (v.1.4.6).. 
> 
> 
> 
> i hope it will be fixed soon..
> 
> 
> 
> thankyou for building this amazing plugin..

Hey,

I don't have access to Android to test it, but on iPhone it should be fixed on the next release.

**Demo:**
https://github.com/xRyul/obsidian-image-converter/assets/47340038/ad641229-1d43-40e1-89ba-e9a641a726be

Thanks for checking out my plugin 🙏
