### ISSUE TITLE
Way to Turn Off right click menu

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [xRyul/obsidian-image-converter#10]
The right click menu is fighting with other plugins for the right click window space :( 
The plugin in the back is Second Window and is much more important for my workflow. 
Is it possible to have a way to turn the right click menu off perhaps?

![image](https://github.com/xRyul/obsidian-image-converter/assets/96321415/086f915c-8123-4fcd-b806-5c6c531ee7ac)

**Comment by xRyul** [comment]
It is already implemented, I just need to release it:

<img width="386" alt="image" src="https://github.com/xRyul/obsidian-image-converter/assets/47340038/fff9a8dc-ca63-477b-a101-fc75bc63ac7f">

<img width="125" alt="image" src="https://github.com/xRyul/obsidian-image-converter/assets/47340038/82364878-ff48-4248-8e7c-c4d1d2fc970d">
