### ISSUE TITLE
Huge images on iPhone

### ISSUE THREAD

**Issue by stefanix** [xRyul/obsidian-image-converter#101]
When pasting an image on iPhone (13 pro max, latest ios) the IC does not seem to honor the quality setting and defaults to a fairly high value (10x bigger image files than 85 on desktop). Same issue for both webp and jpg.

How to reproduce: Paste same image into obsidian with IC active on insert. Compare resulting image size on mobile vs desktop.

**Comment by xRyul** [comment]
I rarely use Obsidian on mobile, thus support will be very limited. 

Current workaround is if size is bigger simply return the array buffer of original. Advanced -> toggle Allow larger file size.
