### ISSUE TITLE
[BUG] Forced shutdown of Obsidian when compressing large files on Android. 9000x12000 (108MP), +- 35MB.

### ISSUE THREAD

**Issue by bav2653** [xRyul/obsidian-image-converter#102]
I have an Infinix Hot 40 Pro phone. It can take photos with a resolution of 9000x12000 (108MP). The photos are approximately 35MB in size.

The Image Converter add-on doesn't process such files on Android. During photo compression, Obsidian forcibly shuts down after 20 seconds.

I tried tweaking the settings, but Obsidian still crashes while processing such photos. There is no such issue on a computer.

Here is the [link](https://drive.google.com/file/d/1-dui-bedR1DnDyPNhzHILs6llGjucKnu/view?usp=sharing) to the photo.

Just in case, I’m sharing my settings. Maybe it’s my fault.
<img src="https://github.com/user-attachments/assets/a348287c-723e-4007-96b7-c6e1c97a1a8a" alt="Screenshot 1" width="100" height="100">
<img src="https://github.com/user-attachments/assets/84974bec-3090-4f7b-97c4-c422e10dea67" alt="Screenshot 2" width="100" height="100">
<img src="https://github.com/user-attachments/assets/2ab770bc-9394-48e5-8ea3-7e5bf9c2f63a" alt="Screenshot 3" width="100" height="100">
<img src="https://github.com/user-attachments/assets/4ab1165f-69ad-47f3-bbb0-824760630ce0" alt="Screenshot 4" width="100" height="100">
<img src="https://github.com/user-attachments/assets/9e808336-0283-4285-a009-c1bc514dd8bc" alt="Screenshot 5" width="100" height="100">
<img src="https://github.com/user-attachments/assets/5798ac6d-e893-4c1f-8b0b-46d5248cf5d9" alt="Screenshot 6" width="100" height="100">

**Comment by xRyul** [comment]
Wow those dimensions are huge 😅


On mobile and desktop the way toblob, todataurl, canvas, blob are treated and rendered is different. Thus it requires custom hacks to make it work and then port it all into Image Converter, hence the discrepancy.

Although, latest release introduces some changes to mobile. So hopefully that will help 🔥 I just tested it on my phone, and it managed to reduce your provided image to about 1mb~ 

![image](https://github.com/user-attachments/assets/576e63bb-7a6a-4245-940f-24ec4ca772dc)

**Comment by bav2653** [comment]
> Wow those dimensions are huge 😅
> 
> On mobile and desktop the way toblob, todataurl, canvas, blob are treated and rendered is different. Thus it requires custom hacks to make it work and then port it all into Image Converter, hence the discrepancy.
> 
> Although, latest release introduces some changes to mobile. So hopefully that will help 🔥 I just tested it on my phone, and it managed to reduce your provided image to about 1mb~
> 
> ![image](https://private-user-images.githubusercontent.com/47340038/389303140-576e63bb-7a6a-4245-940f-24ec4ca772dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTYwOTEsIm5iZiI6MTczMjU1NTc5MSwicGF0aCI6Ii80NzM0MDAzOC8zODkzMDMxNDAtNTc2ZTYzYmItN2E2YS00MjQ1LTk0MGYtMjRlYzRjYTc3MmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE3Mjk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZjY1NDA0NjMxMDgyYmVhNWZiNjAzOWQyNjkxMjAzYmFiNjMwNGNmMmU2YzRlMTAzNWViMmE5NDdiNDg5NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pXD-uTdQID9-9GT8Uxv_TaNMps9xaWwiYQG4oMqz1rY)
> 
> Please try update to the latest release [1.2.9](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.9) and see if that helps. Just leave all settings on default in Advanced tab, except "Allow larger file sizes after conversion" toggle it OFF.
> 
> Conversion might take some time, due to the resolution and we are only processing on single core, but hopefully it should not fail.

I owe you an apology. I tried update 1.2.9 and was about to report that the add-on still doesn’t compress large files. However, I decided to keep only your add-on enabled.  

Yes, large files are being compressed. It turns out that another add-on, **[Creases](https://github.com/liamcain/obsidian-creases)**, interferes with your add-on's functionality. Perhaps you can do something about it, as **[Creases](https://github.com/liamcain/obsidian-creases)** hasn’t been updated in over a year.  

If you know of an alternative add-on that can automatically collapse headings when opening a note, that would also be a good solution to the problem.


Thank you for your hard work 🙏🏻
