### ISSUE TITLE
[Bug] Image resizing stopped working all of a sudden

### ISSUE THREAD

**Issue by moeiniamir** [xRyul/obsidian-image-converter#108]
I believe that, due to an update, non-destructive image resizing has stopped working when pasting an image if the “Convert to” setting is set to “Same as Original.”

Plugin version: 1.2.11
Obsidian version: v1.7.7
Installer version: v1.5.3
Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 23.6.0

**Comment by xRyul** [comment]
Should be fixed in the [latest release](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.12). 

I am closing it for now. If you still encounter any issues, please comment back ❤️🙏
