### ISSUE TITLE
[Bug] Non-destructive resizing during drag-resize or scroll-wheel uses longest edge for portrait images causing render discrepancy between preview and reading mode

### ISSUE THREAD

**Issue by mozzaren** [xRyul/obsidian-image-converter#109]
When an image is taller than wider, resizing it by dragging the edge or scrollwheeling does not work properly. I think it is because the plugin is using the longest side of the image as the size value rather than just the width.
![GIF 12-1-2024 3-27-13 PM](https://github.com/user-attachments/assets/adc90614-801f-46d0-80c2-6ef542ed3d68)

**Comment by xRyul** [comment]
Well spotted, and thanks for reporting. 

At some point I wanted to add many more non-destructive resizing options and never got to it

| width
| widthxheight
| widthxheigh - based on longest edge
| widthxheigh - based on shortest edge

If you cannot wait for the next release -> this should fix it:
[main.zip](https://github.com/user-attachments/files/17970460/main.zip)

**Comment by mozzaren** [comment]
Thanks and great work!

**Comment by xRyul** [comment]
It should be now fixed in [1.2.13](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.13) 🚀
