### ISSUE TITLE
Conversion doesn't retain transparency. 

### ISSUE THREAD

**Issue by terrybjr** [xRyul/obsidian-image-converter#11]
Any images that have transparent backgrounds convert to white backgrounds with this plugin. This makes the plugin un-usable for my purposes. Everything else looks great though!
<img width="385" alt="image" src="https://github.com/xRyul/obsidian-image-converter/assets/44714406/935a02a6-8655-45e8-b77d-7e84edab27dd">

<img width="523" alt="image" src="https://github.com/xRyul/obsidian-image-converter/assets/44714406/0ec5c0f6-10d5-4f12-bf98-c36f7ea5c59e">

**Comment by juanbretti** [comment]
Which image format are you using?

**Comment by terrybjr** [comment]
This is from png to webp, or png to png. Both cases create this white background. But if I paste the png into obsidian by itself without using the module it pastes without the background. 

My specific use case is copying the images out of a rpg pdf. This copied the png. The dark image above of the woman without the beck ground is me pasting the raw image into one note just to prove the image has a transparent background.

**Comment by xRyul** [comment]
Fixed with [Release 1.1.5](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.1.5)
