### ISSUE TITLE
Convert gif files animation into static images

### ISSUE THREAD

**Issue by ATaimasov** [xRyul/obsidian-image-converter#114]
Hello! 

Your app is cool and very useful!
It is comfortable to use, but I meet one painful problem. If I insert gif files (animations), they turn into static images. 
I have not noticed this problem before. That being said, I often insert both animations and static files

I hope that you can fix it.

**Comment by xRyul** [comment]
Hey, I am happy that you find it useful 🚀

This has been already reported a few times, latest one is https://github.com/xRyul/obsidian-image-converter/issues/89

From version 1.2.15 you will be able to skip images based on pattern (glob or regex), something like "If image contains certain word or character ->please skip it from processing" e.g. to skip GIF images you will be able to say:

`*.gif` - to skip gifs from processing
`/cat/`  - to skip processing **only** gifs with certain word  e.g.: "MyAwesomeGif-of-a-cat-01.gif" <- this would not get processed

Although this is still 2 releases away 😭

I will close this for now. If you have further suggestions - feel free to comment back.
