### ISSUE TITLE
[BUG] Non-destructive resize: image wont get resized if "image name with extension" is already in note as plain text

### ISSUE THREAD

**Issue by caglarongan** [xRyul/obsidian-image-converter#120]
This bug came up while using with another plugin, see : https://github.com/johansan/obsidian-featured-image/issues/5#issuecomment-2539761933

**Comment by xRyul** [comment]
Hey, many thanks for reporting. I am able to reproduce the example he provided there:

e.g.:

```
Some text mentioning example.jpg in a paragraph
Another paragraph

![[example.jpg|100]]  # This link would not get resized
```

But not sure what do you mean about frontmatter?

**Comment by johansan** [comment]
Hi xRyul,

Thanks for the quick fix. My plugin "Featured Image" automatically creates a frontmatter property from the first image, image link, Youtube link or Auto Card Link image in the document. 

So if you have ![[example.jpg|100]] in your document, my plugin would create one of two frontmatters (you can choose the format style in plugin settings):

```
---
feature: ![[example.jpg]]
---
![[example.jpg|100]]
```

or
```
---
feature: example.jpg
----
![[example.jpg|100]]
```

The name of the property can also be changed (e.g. it does not have to be called "feature"). Use cases for my plugin is for headers, dataview lists, and more.

If possible you should exclude the frontmatter section when resizing, so it does not try to update the image link in there, for example using:

        let contentWithoutFrontmatter = content;
        if (content.startsWith('---\n')) {
            const frontmatterEnd = content.indexOf('\n---\n', 4);
            if (frontmatterEnd !== -1) {
                contentWithoutFrontmatter = content.substring(frontmatterEnd + 5);
            }
        }

Thanks, I love your plugin by the way, it's amazing!

**Comment by xRyul** [comment]
Hey, many thanks for all the kind words and stopping by 🙏 

I rarely use frontmatter, hence why probably I never even noticed. But completely understand the importance of it, and do agree that we shouldn't touch it. From 1.2.20 + it will skip any image links found within the frontmatter section (this should help with frontmatter integrity) and only resize images in the main content of the note. 

https://github.com/user-attachments/assets/c8d2cd3f-4de8-4ffe-b19c-10d108ded703

**Comment by johansan** [comment]
Amazing, many thanks!
