### ISSUE TITLE
[Feature request] Process all images in Canvas

### ISSUE THREAD

**Issue by Hela-Girl** [xRyul/obsidian-image-converter#122]
Please tell me when it will work for canvas?

**Comment by xRyul** [comment]
Hey, is there anything in particular that doesn't work?

You might find following comment useful: https://github.com/xRyul/obsidian-image-converter/issues/50#issuecomment-2455770223

**Comment by Hela-Girl** [comment]
I click:
https://i.imgur.com/SmLblBV.jpeg
and I receive
https://i.imgur.com/hwaUZa1.jpeg

What am I doing wrong?

**Comment by xRyul** [comment]
From 1.2.21 you will be able to process all in canvas, or all in folder, all in note etc..

**Comment by Hela-Girl** [comment]
How to download version 1.2.21? 
Or were you talking about a future version? which one will be released in 2027?  (Joke)

**Comment by xRyul** [comment]
It is not available for general release. Currently only supporters of the project, get access to the latest updates and features. 

1.2.21 hopefully will be out sometime in January~

**Comment by Hela-Girl** [comment]
Great marketing buddy, I like your approach 👍

**Comment by Hela-Girl** [comment]
I have a different approach, I will become a subscriber when I understand that there is a script that works as I need. I’ve already supported people several times, but they only fed me promises that everything would be fixed soon and it would work perfectly.
