### ISSUE TITLE
How can I prevent it from reducing quality of my embedded images?

### ISSUE THREAD

**Issue by Cassis692** [xRyul/obsidian-image-converter#130]
“Output format” I choose same as original(will choosing webp lose quality?)
“Compression level” I choose 100(then 75, which I found won’t compress my image??)
Can someone explain something, and tell me how to do?(Compressing isn’t necessary, I just want my image to be of its fullest quality)

**Comment by xRyul** [comment]
For "the best all-around leave-it-and-forget-it compression and quality ratio" it is best to leave it on default, and turn off "Allow larger file sizes after conversion" in Advanced. 

For more in depth answer, all your questions are already answered: 
- [Examples/How to compress images without quality loss - empirical analysis of image format vs image quality vs file size.md](https://github.com/xRyul/obsidian-image-converter/blob/master/Examples/How%20to%20compress%20images%20without%20quality%20loss%20-%20empirical%20analysis%20of%20image%20format%20vs%20image%20quality%20vs%20file%20size.md)
- [Notes on file sizes.md](https://github.com/xRyul/obsidian-image-converter/blob/master/Notes%20on%20file%20sizes.md)
