### ISSUE TITLE
The add-on does not work in my database 😢

### ISSUE THREAD

**Issue by bav2653** [xRyul/obsidian-image-converter#139]
The add-on works incorrectly with my database, but it functions normally in the sandbox.
Perhaps you can advise me on what to do 🙏🏻🙏🏻🙏🏻

All third-party add-ons are disabled except for yours.
All CSS snippets are turned off.
Standard theme is applied.

Half of the functions from the context menu do not work, including:
- Renaming a file
- Show in novigacion
- Show in sustem explorer
- Deleete image from vault

https://github.com/user-attachments/assets/0c5b479e-f8a5-4c7b-b0f8-444d6e2beb9e

**Comment by bav2653** [comment]
I found a solution. I simply renamed the database. Previously, it was named "OBSIDIAN."

**Comment by xRyul** [comment]
In your Obsidian vault you have Native menus turned ON, in your other vault your have it OFF. Native menus do not support custom CSS or HTML, hence the blank, and why those options do not appear.

**Comment by Danie10** [comment]
Glad I found this issue. I had same problem with native menus on. Tuning that off, it works fine now.
