### ISSUE TITLE
[QUESTION] Is there a way to include subfolder in the file location?

### ISSUE THREAD

**Issue by lduperval** [xRyul/obsidian-image-converter#14]
Hi,

Is there a way to include the subfolder in the name of the file for compatibility purposes? For examples, if I ask to put the file in the "images" subfolder, the file is stored there but the Markdown does not include the subfolder name. So if I open the file in a different app, the contnt is missing.

Thanks,

L

**Comment by xRyul** [comment]
Just for clarification, lets assume if I drop "image.jpg" into note called "MySampleNote.md":

- You want image to be stored inside `/images` subfolder and then its name to be auto-renamed to {foldername}{notename}{date} ? 

- Thus "images.jpg" would become "images-mysamplednote-YYYYMMDD.jpg"?

Various options for file renaming are in the roadmap, although can't provide exact date right now

**Comment by xRyul** [comment]
Thanks for the clarification. Should be possible to implement this,
although not sure about forward slash “/”, Obsidian doesnt allow certain
special characters to be used in the name e.g “/\:” are not allowed, hence
most likely would need to use “-” or “underscore” instead.

Gonna have to investigate it further

**Comment by lduperval** [comment]
Actually, the "images/" is not part of the name. It's the folder specified in the config. It could be anything.

Thanks!

L

**Comment by xRyul** [comment]
I think I finally got it 😅 

`doctor-listening-to-patient-heart.jpg`
↓
`doctor-listening-to-patient-heart.webp`

1. To preserve the original name you can simply turn off: **Auto rename**
2. If **images/** doesn't have to be in the name, you can put the image into `images/` subfolder via: 
a) "Output" -> "In the folder specified below:" then type in "/images". This will allow you to store all images inside this folder, regardless in which note they are located.
b) "Output" -> "In subfolder under current folder" then type in "/images".  If you have many folders in Obsidian, and each folder represents a category/project, then this option might be great for you. It will create a subfolder under current note, or if the note is inside the folder, then it will create subfolder inside this folder. Thus essentially allowing your images to follow your "projects". 

https://github.com/xRyul/obsidian-image-converter/assets/47340038/b7aa521f-4d19-4b4d-b00b-243cab65ad24

**Comment by lduperval** [comment]
Oh, that's simpler than I thought! Thanks!

**Comment by lduperval** [comment]
Hi again,

I have another question. Above you say that if "images/" doesn't have to be in the name I have a couple of options. But what if I do want "images" to be part of the name (which is what I want for compatibility with other editors)? 

Thanks!
