### ISSUE TITLE
Command "Process all images in current note" does not obey folder location setting

### ISSUE THREAD

**Issue by brucetm** [xRyul/obsidian-image-converter#140]
Processed images are always dumped into vault root, regardless of plugin settings: Default Location is ignored, as is any Custom Location specified. 

However, on paste of an image into note, the plugin does follow either setting specified above. Only when using the command, is the location always ignored. 

Here are the settings used, and before and after using the command, where you can see the attachments folder path is stripped:

![Screenshot 2024-12-27 at 8 38 59 AM](https://github.com/user-attachments/assets/4070c0bb-2c33-4f1f-b204-59df65e5ded4)

![Screenshot 2024-12-27 at 8 39 35 AM](https://github.com/user-attachments/assets/a0b6bdb2-240e-497e-b560-94cd92a4bb99)

![Screenshot 2024-12-27-1 at 8 40 18 AM](https://github.com/user-attachments/assets/9209b9f2-c382-4c21-bc77-0ce0cb2f8671)

![Screenshot 2024-12-27 at 8 40 43 AM](https://github.com/user-attachments/assets/825a7021-c1d5-4655-b6a6-60a1e9b45bb7)

![Screenshot 2024-12-27-1 at 8 41 01 AM](https://github.com/user-attachments/assets/fda2929f-6cb3-431b-89e8-d917e1661cd9)

![Screenshot 2024-12-27 at 8 42 02 AM](https://github.com/user-attachments/assets/dbaaa154-fbc3-4a38-8a5e-5209e59ac44c)

**Comment by xRyul** [comment]
Hey, many thanks for checking out the plugin! 

"Process all images in current note" can only convert, compress and resize images. It will not move images - that is by design for safety reasons.

**Comment by brucetm** [comment]
Two questions:

if not moving them is by design, why does the plugin offer custom image destinations in settings? What are those overrides for?

if it’s not supposed to move them, why does it move all converted images out of attachments folder and into root? See screenshots above.

**Comment by xRyul** [comment]
1. Output options in the Settings are for drop/paste. When they are added in this way, it is possible to detect all imaged immediately in 1 action (and then process them then and there), but when processing all images in the note/canvas/folder/subfolder is completely different. It involves various linking syntaxes, different file formats, plugins, and various sync options used by each user. Adding **move** option for every "custom'ly added" image into every individual users vault/note would be a disaster waiting to happen. 

2. I see you are on the older Image Converter version, does the same happen on clean up-to-date version too? Currently I am unable to reproduce. Plugin shouldn't move when processing images in batches. I noticed you also use "shortest links" but in the example provided the image uses relative link. I tested it on both, and still couldn't reproduce. I see you also have Local Images Plus plugin enabled which also has option to move images, have you disabled those?

https://github.com/user-attachments/assets/d1ecd9ae-2724-4c1d-987c-29507737687a

**Comment by brucetm** [comment]
1. I don't understand why various plugin actions have different rules. I think you should identify on the plugin settings page which commands the settings are valid for. Per your other point about moving: I'm not asking for it to move things, but to not move things out of the attachments folder and dump them into root. Perhaps it does this if there are other images of the same name? That would make some sense.

2. Sorry, new to Obsidian, did not know that they don't have auto update for plugins. Will update and try again and report back here, thank you! And thank you for the screenshare, I will make one too if I still see the issue, perhaps you can spot what I'm doing. 

Your time is much appreciated, this plugin is super useful. I will do a github donation for it!

**Comment by xRyul** [comment]
Many thanks! 

Initially plugin was meant to work only on drop/paste. But since then it has grown significantly. Hence, why some of the settings might seem like they are all over the place. 

Convert to/Output/Non-destructive resize - only works on drop/paste. Other options like right-click, notifications are more global.

Any batch processing command, whether accessed via command palette or via right-click by clicking on folder/note/image file - they all uses completely different code irrespective of one another. Every batch processing command is like separate plugin of its own. 

As for moving/not moving outside attachment folder. None of the the batch commands have this feature, which means the behaviour is most likely being triggered by interference of another plugin which tries to take over the attachment management.
