### ISSUE TITLE
Zoom functionality breaks when using the Blue Topaz theme alongside the Image Converter.

### ISSUE THREAD

**Issue by bav2653** [xRyul/obsidian-image-converter#143]
Hello 👋🏻

You have added a new feature to your add-on that zooms images during viewing 👏✨

Please 🙏🏻 provide the ability to disable this feature, as I am not yet accustomed to it and still rely on the zoom functionality of the "Blue Topaz" theme with "Style Settings".
Unfortunately, when using your add-on with this theme, the zoom functionality breaks.
![Obsidian_zni1SOvSo3](https://github.com/user-attachments/assets/7d6ca9ab-a9b2-4e73-8b10-24deee4e2890)
___
You are turning a narrowly focused add-on into a Swiss army knife. Please give us the ability to disable unnecessary features.

For example, if I had the option to disable other features, I would remove the following:
![Obsidian_GJCHHJ0IDr](https://github.com/user-attachments/assets/25907add-7eb3-40a7-8994-c35ee0b06783)

**Comment by xRyul** [comment]
The feature you are showing - zooming when clicking in the middle of an image - Image Converter has no such feature. As for customizing right-click it will be possible, but not just yet: https://github.com/xRyul/obsidian-image-converter/issues/104

**Comment by bav2653** [comment]
> The feature you are showing - zooming when clicking in the middle of an image - Image Converter has no such feature. As for customizing right-click it will be possible, but not just yet: #104

Yes, the add-on does not center the image when zooming, but it has a stretching feature that interferes with the proper functioning of Blue Topaz.

Your add-on has changed a lot for me, and now I can't do without it, but I still need image zooming to be centered on the screen. Please consider giving us the option to disable features that are unnecessary for us.

**Comment by xRyul** [comment]
What do you mean by "stretching image"? 

If you don't want to be able to resize images via dragging edge of the image or via scroll wheel - just disable it in the Settings.

![image](https://github.com/user-attachments/assets/94749a68-8e06-4e74-8a42-153b3aad2c03)

**Comment by bav2653** [comment]
> What do you mean by "stretching image"?
> 
> If you don't want to be able to resize images via dragging edge of the image or via scroll wheel - just disable it in the Settings.
> 
> ![image](https://private-user-images.githubusercontent.com/47340038/399157229-94749a68-8e06-4e74-8a42-153b3aad2c03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1MDE5NzEsIm5iZiI6MTczNTUwMTY3MSwicGF0aCI6Ii80NzM0MDAzOC8zOTkxNTcyMjktOTQ3NDlhNjgtOGUwNi00ZTc0LThhNDItMTUzYjNhYWQyYzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDE5NDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NzExNWVlNGVmMTJlODQxNDI3NzJmZDkzNDE2MDJmY2U4YThmYjZkOTRiMzQyOTgyZGFjYmJlYmVhMDA3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2al1FgI84ca8ifF04sWOLT8cmYqmatWSioApzYk8ejk)

Yes, I’m talking about this feature.
I believe that after its introduction, Blue Topaz began to work incorrectly.

I just installed version 1.2.16, and Blue Topaz works fine there.
In version 1.2.17, Blue Topaz starts having issues. In this version, you added three new features, and one of them disrupts Blue Topaz’s functionality:

- In lists, the dot will not be in the middle, but at the TOP! Possibly in the future, users will be able to specify where they want it to appear: bottom, middle, or top.
- Ability to resize images in Reading Mode, and it will also resize in Live Preview. For it to work, simply apply any alignment to the image so it can then be stored in the cache.
- Text wrapping around images.

![Obsidian_wPjN4PJPs4](https://github.com/user-attachments/assets/de438def-698b-4e64-9e21-f258fa55a800)

**Comment by bav2653** [comment]
After the update to 1.2.24, Blue Topaz started working fine. Thank you 👍🏻
