### ISSUE TITLE
[FEATURE REQUEST] Keep the basename of the image

### ISSUE THREAD

**Issue by lduperval** [xRyul/obsidian-image-converter#15]
Hi,

Is it possible to use the basename of the image when renaming instead of using the name of the file? So if I paste (or drag and drop) this file

my_very_long_name.png

I would like it to be renamed as

my_very_long_name.webp

Thanks,

L

**Comment by xRyul** [comment]
Thanks for testing out the plugin! 

I have already implemented it, just need to push out the new release

**Comment by xRyul** [comment]
Turning off Autorename will now preserve original name and still allow to compress or resize 

[Release 1.1.6](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.1.6)
