### ISSUE TITLE
[FEATURE REQUEST] File naming: Add output/destination subfolder name into the filename

### ISSUE THREAD

**Issue by jiajiala** [xRyul/obsidian-image-converter#19]
/assets/${filename}_assets

As above, I set the attachment on attachment location

Hopefully the converted files will also be in this folder

![image](https://github.com/xRyul/obsidian-image-converter/assets/73203026/3e428c51-1b56-46a4-8747-8fecb05043b9)

**Comment by xRyul** [comment]
I was looking into it. Not sure when I would release it yet, but it would be under variable {subfolder}, so then user would be able to build their own desired filename structure via variables:

`{Filename}{Filename With Ext}{Filename Number}{Directory}{Folder name}{Accessed Date}{Creation Date}{Modified Date}{Size}{Size B}{Size KB}{File Type}{Current Date}{Color Model}{Compression}{Width}{Height}{DPI}{Ratio}{EXIF}{IPTC}`

Also which plugin is in the screenshot? It manages all folder structure and file naming in 1 input field - I would be separating the 2.

**Comment by amccaugh** [comment]
This would be really helpful, and cut down on the number of options you need to specify in the default dropdown, would definitely be interested in this

**Comment by xRyul** [comment]
Option to create custom filenames and output folder structures via variables is now available in [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/latest). For currently supported variables please check settings of the plugin or [this doc](https://github.com/xRyul/obsidian-image-converter/blob/master/Examples/Variables%20Reference%20Guide.md) . 

![image](https://github.com/user-attachments/assets/e57461c9-f2ad-4f01-bbda-407487ae2511)
![image](https://github.com/user-attachments/assets/f24f45f3-2152-4b15-b31f-6f570bedda59)
![image](https://github.com/user-attachments/assets/bda62be3-3ba2-4488-844a-a880831d3fdd)
![image](https://github.com/user-attachments/assets/032f07ec-cf12-415a-801d-d2043871646d)
