### ISSUE TITLE
very nice! thank you very much!

### ISSUE THREAD

**Issue by dotkt** [xRyul/obsidian-image-converter#21]
it's very nice ,it save my time,it save my life!
thank you very much.

**Comment by dotkt** [comment]
This project is great, can it support inserting multiple images at once?

**Comment by dotkt** [comment]
This project is great, can it support inserting multiple images at once?

**Comment by Flecart** [comment]
@dotkt Yes it can.

@xRyul do you plan to keep maintaining this project? For example this PR could be closed.
