### ISSUE TITLE
when mouse slides over an image,the window to adjust the image size automatically open

### ISSUE THREAD

**Issue by amacelite** [xRyul/obsidian-image-converter#22]
On mac os, when the mouse slides over an image, a window to adjust the image size will automatically open, which greatly affects the reading experience.It seems to be due to conflict with image tookit  https://github.com/sissilab/obsidian-image-toolkit

**Comment by xRyul** [comment]
Fixed with [Release 1.1.7](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.1.7)
