### ISSUE TITLE
Idea: Including batch conversion when several png are inserted at one go

### ISSUE THREAD

**Issue by dimkaart** [xRyul/obsidian-image-converter#27]
As the title states, do you think it would be possible to add batch converting when several images are draged at the same time into a obsidian note?

**Comment by xRyul** [comment]
Hey, thanks for checking out the plugin. It is possible, and hopefully will be implemented in the next release: For info you can follow[ this](https://github.com/xRyul/obsidian-image-converter/pull/24) pull request, where @dotkt had implemented it.

**Comment by xRyul** [comment]
Ability to drop multiple images implemented in [1.1.7](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.1.7)

If you encounter any issues, or suggestions feel free to get back to me 🙌
