### ISSUE TITLE
BUG: Image converter interferes with Image inserter plugin

### ISSUE THREAD

**Issue by materemias** [xRyul/obsidian-image-converter#28]
See https://github.com/cloudy9101/obsidian-image-inserter/issues/24 . Basically, image-converter causes to select the hovered image instantly and without click

**Comment by xRyul** [comment]
Hey, this issue should only exists on Externally embedded images. Although, regardless, it will be fixed on the next release. Hopefully should be able to compile all and release on Monday 23rd~ 

Thanks for reporting!
