### ISSUE TITLE
can this plugin support placing the image in  the attachment folder under the note folder?

### ISSUE THREAD

**Issue by amacelite** [xRyul/obsidian-image-converter#3]
that would be so useful

**Comment by xRyul** [comment]
Great suggestion. Going to add this to my todo list! Although, currently I am more focused on implementing better algorithms for better image compression and smaller file sizes, so can't give an exact date when! 

Many thanks for testing out the plugin!

**Comment by xRyul** [comment]
> that would be so useful

Just realised that this is already possible by default Obsidian behaviour:


>You can change the default attachment location under **Settings → Files & Links → Default location for new attachments.**
>- **In subfolder under current folder** adds attachments to a specified folder next to the note you added the attachment to. If >it doesn't exist, Obsidian creates it when you add an attachment.
 https://help.obsidian.md/Editing+and+formatting/Attachments

**Comment by amacelite** [comment]
> > You can change the default attachment location under **Settings → Files & Links → Default location for new attachments.**
> > 
> > * **In subfolder under current folder** adds attachments to a specified folder next to the note you added the attachment to. If >it doesn't exist, Obsidian creates it when you add an attachment.
> >   https://help.obsidian.md/Editing+and+formatting/Attachments

but when use the “image converter”, the obsidian setings  is no longer working, the image is placed in the root directory or the directory specified by the image converter settings

**Comment by xRyul** [comment]
Thanks, gonna look into it

**Comment by xRyul** [comment]
Added 2 options:
1) If you want to have all images, videos, gifs, audio files etc. be in 1 specific folder: 
    -  In Plugin Settings make sure "Output" is set to "**Default**"
        <img width="480" alt="Screenshot 2023-09-22 at 12 08 46" src="https://github.com/xRyul/obsidian-image-converter/assets/47340038/0c88ff57-966f-4ae3-ae7e-8c3ec13cea74">
    This will tell plugin to follow default Obsidian Settings: "Files & Links" -> "Default location for new attachments"

2) But if you would like to separate images from other attachment files. You can select 1 of 4 options. All options, mimic similar behaviour as and default Obsidian settings.
   - **Root folder**: adds the processed **images** to the root of your vault
   - **In the folder specified below**: adds the processed **images** to a custom directory. For example, if you specify `Attachments/images`, then all image files will be saved in this directory. If any of the folders do not exist, they will be created. 
   - **Same folder as current file**:  adds the processed **images** to the same folder as the note you added it to. For example, if your note is located in `00-HOME/Subfolder1/note.md`, the image will be saved in `00-HOME/Subfolder1/`
   - **In subfolder under current folder**: adds  the processed **images** to a specified folder next to the note you added the attachment to. If any of the folders do not exist, they will be created. For example, if your note is located in `00-HOME/Subfolder1/note.md`, and I specify that i want to keep all images inside "images" subfolder, then the image will be saved in `00-HOME/Subfolder1/images/`.
