### ISSUE TITLE
BUG: time format has 3 extra digits

### ISSUE THREAD

**Issue by blumenschwein** [xRyul/obsidian-image-converter#30]
* System: Ubuntu 22
* Obsidian version: v1.4.16
* Image converter version: 1.1.6

When using `auto rename`, the generated file name has a suffix which is supposed to have the format YYYYMMDDHHMMSS, but I got three more digits. For example, in the file name `my_note-2023-10-20231021102417842.jpg`, "842" is the three extra digits. Is there a way to remove them?

Or even better: Is it possible to use regular expression to specify the format of the converted file name? Thanks a lot.

**Comment by xRyul** [comment]
Hey, thanks  for checking out the plugin.

In current implementation the correct output should be in: `YYYYMMDDHHmmssSSS` so the 3 digits at the end are actually correct, and documentation is simply wrong - I gonna have to update it 🙏 With the latest release 1.1.7 , the milliseconds are needed for multi-drop to work correctly e.g.: to prevent having files with the same name 

Support for various naming conventions/formats is currently WIP. Although, I will add "_regular expression to specify the format of the converted file name"_ to my to-do list 🎉
