### ISSUE TITLE
[BUG] Plugin doesn't work in separate windows

### ISSUE THREAD

**Issue by willc** [xRyul/obsidian-image-converter#31]
If I select "Open in new window" for a given note, this plugin doesn't convert any images pasted into that window. Same is true of any tabs in that same separate window.

**Comment by xRyul** [comment]
Hey, thanks for reporting! I will look into it.

**Comment by Kenji-Takatou** [comment]
The same problem occurs to me.
Although "Process all images in current note" works for images in pop-out windows as well, they are not converted automatically.

Anyway, thanks for the very useful plugin!

**Comment by juanbretti** [comment]
Same issue here.

**Comment by xRyul** [comment]
This will be fixed in 1.2.23
