### ISSUE TITLE
Does not process all images when many pasted at once

### ISSUE THREAD

**Issue by gavinwright-engr** [xRyul/obsidian-image-converter#32]
When I paste in any more than 2 large .HEIC images at one time, they do not get converted to the format selected.

**Comment by xRyul** [comment]
Thank you for reporting 🙏 Fixed it by adding a queue for each image to be processed. Will be available in the next release 💪 c58e9fffa96c58984d9449e7e9ec24122ac516d2

Although, converting multiple HEIC files in Obsidian it is quite an intensive task, until I gonna implement workers to speed it up - I would recommend to use dedicated software for that, something like: [XnConvert](https://www.xnview.com/en/xnconvert/)
