### ISSUE TITLE
No-compression HEIC conversion causes broken preview

### ISSUE THREAD

**Issue by gavinwright-engr** [xRyul/obsidian-image-converter#33]
<img width="702" alt="Screenshot 2023-11-12 at 3 09 13 PM" src="https://github.com/xRyul/obsidian-image-converter/assets/68081139/cd8e4112-61a2-4eb5-8ef1-de9fd9045b81">

**Comment by xRyul** [comment]
Fixed with 1c2991cc795f59f4f694537d3ac6927b58a82474 Will be available in the next release 💪

Thank you for reporting 🙏

**Comment by gavinwright-engr** [comment]
Thank you! Do you know when the next release will be?
