### ISSUE TITLE
[BUG] "| size" not being applied to certain links

### ISSUE THREAD

**Issue by gerroon** [xRyul/obsidian-image-converter#36]
Hi

I use the borders to scale the image in the page, it works initially but after that it resets back to the original size. I am not why that is the case.

I use it on Win 11, Obsidian 1.4.16

**Comment by xRyul** [comment]
Hey,

Thanks thanks for checking out the plugin and reporting it 🙏

Are you trying to resize them in Reading Mode by any chance?

**Comment by gerroon** [comment]
Hi

I use the Live edit mode.

**Comment by strongMuscle110** [comment]
@gerroon @xRyul temporary fix:

---> [x] Options/ Files and links/ Use[[Wikilinks]]

seems like the plugin can only target wiki-link-style, md-link-style ignored

**Comment by deafmute1** [comment]
This 

> @gerroon @xRyul temporary fix:
> 
> ---> [x] Options/ Files and links/ Use[[Wikilinks]]
> 
> seems like the plugin can only target wiki-link-style, md-link-style ignored

This isn't a fix for me, it doesn't append the pipe value to the link, even with wikilinks, even in live edit. 

This [plugin](https://github.com/nicojeske/mousewheel-image-zoom) implements just this feature and works fine.

**Comment by xRyul** [comment]
Hey, [latest release](https://github.com/xRyul/obsidian-image-converter/releases/latest) adds better support for MD and WIKI links + shortest vs relative paths.  Both drag resize and scroll wheel should now work fine. You can now also assign any other mod key to scrollwheel resize and set desired cursor position e.g. front of the link or back of the link.

https://github.com/user-attachments/assets/ddd2dad8-3135-4588-9790-2f4282feed2f

If issue still persists, please provide with exact link and filename examples.

**Comment by xRyul** [comment]
I am closing it for now and marking as fixed, if issue still persists please provide exact use case scenarios with example image files and links.
