### ISSUE TITLE
Quick question: Could I ask about the release plan?

### ISSUE THREAD

**Issue by juanbretti** [xRyul/obsidian-image-converter#37]
Hey,
**Congratulations** to all for the great project and progress.

I would like to know when you are planning to release all the latest advances in development.
I see lots of new additions to the code that are pending release.

Thank you again!

**Comment by juanbretti** [comment]
Hello @xRyul ,
Hope you are doing great!
Looking forward to your next release on this awesome plugin!
Regards,

**Comment by xRyul** [comment]
Hey, 

I haven't forgotten about this project. 

I was in the middle of rewriting it when some big life events happened + obsidian changing some of its API didnt help either. Currently, I've quit my job to go back to Uni - whether this will allow me to focus more on this project I am yet to find out.

I still use this plugin myself, and I still use Obsidian on a daily basis, so if there will be any major update from Obsidian itself - with any breaking changes - I will make sure to update it. 

My first priority right now is to go through the PRs and see where I have left off and how they all blend into the current state and future of the project as a whole.  Then go through the bugs, and only later look into FRs.

Many thanks for reaching out!

**Comment by juanbretti** [comment]
@xRyul , happy to know you are doing great.
My absolute best wishes to your new challenge, going back to the University.

Regarding this project: I also use it every single day (multiple times a day).
Super happy you started this project... and I'm happier to know that you are also an intense user of it.

Let your community know if we can help.
Regards!

**Comment by juanbretti** [comment]
Exited to test all the changes you are making to this amazing plugin! 
Thanks!
