### ISSUE TITLE
[FEATURE REQUEST] Add canvas support: No images found in the vault

### ISSUE THREAD

**Issue by Hela-Girl** [xRyul/obsidian-image-converter#39]
https://i.imgur.com/xFQHP1U.jpg

I tried to compress the image on the canvas but for some reason it doesn’t find the images, what am I doing wrong?

**Comment by xRyul** [comment]
Now supported in [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0)

For small demo, and for things to keep in mind when using images in Canvas see my reply in: https://github.com/xRyul/obsidian-image-converter/issues/50#issuecomment-2455770223
