### ISSUE TITLE
JFIFICC_PROFILE0... instead of image file .md file is generated instead of the image file.

### ISSUE THREAD

**Issue by Akiyam-hub** [xRyul/obsidian-image-converter#41]
Hello,
 If you paste the image and try to convert it
the following file is generated instead of the image file.

The settings are as follows.

Obsidian v1.4.16
plugin Version: 1.1.7
OS:: Mac OS Monterey 13.6.1(intel 16inch)

[JFIFICC_PROFILE0....md.md](https://github.com/xRyul/obsidian-image-converter/files/13695039/JFIFICC_PROFILE0.md.md)

<img width="928" alt="20231217160518" src="https://github.com/xRyul/obsidian-image-converter/assets/53425804/12494477-73de-4b0c-a079-d563c2e1b429">

**Comment by xRyul** [comment]
Without seeing the original image file it is hard to tell, however the latest release fixes many bugs, please try it out. And if you still get the same generate .md file, please get back to me 🙌
