### ISSUE TITLE
[FEATURE REQUEST] Mobile Feature Request: Convert when image "shared to" Obsidian from another app (ie gallery)

### ISSUE THREAD

**Issue by adrienneteicher** [xRyul/obsidian-image-converter#43]
At the moment, if I share an image to an Obisian note using the "share" option in a given program, like the Android gallery app, the Obsidian Image Converter does not convert the image automatically. This would be useful to me.#

Thanks!

**Comment by ksi** [comment]
Yeah, it would be great!

**Comment by xRyul** [comment]
This should now work on the [latest version](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0)

Although tested only on iPhone -> From Photos to Obsidian.
