### ISSUE TITLE
[FEATURE REQUEST]: allow file renaming format

### ISSUE THREAD

**Issue by Flecart** [xRyul/obsidian-image-converter#45]
Allow user to specify the format used to rename it.

**Comment by progecon** [comment]
I send this request. Automativally renaming to my wishes would reduce a lot of clicking I need to do

**Comment by fareesh** [comment]
I needed this too - I created a PR for it

https://github.com/xRyul/obsidian-image-converter/pull/55

**Comment by xRyul** [comment]
Many various possible options added in the [latest release](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0). You can build custom folder paths and filenames using variables like: {noteName}, {imageName} etc. Automatically organise images into folders based on their size, date, time etc. Various hashing options available too: MD5, hex, uuid etc...  Some examples can be found [here](https://github.com/xRyul/obsidian-image-converter/blob/master/Examples/Variables%20Reference%20Guide.md)


https://github.com/user-attachments/assets/cf3aab44-0dc1-4b3f-9646-17c82d6917ae


Related: https://github.com/xRyul/obsidian-image-converter/issues/74
