### ISSUE TITLE
[FEATURE REQUEST] Disable in reading view.

### ISSUE THREAD

**Issue by d3Xrr** [xRyul/obsidian-image-converter#46]
Would like to be able to disable the plugin in reading view to not accidentally resize images.

**Comment by xRyul** [comment]
Added a special toggle in [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0)  to disable drag and scrollwheell resizing in Reading view.

![image](https://github.com/user-attachments/assets/15e5abc7-45bd-450c-b45f-09a3e34b9f5c)
