### ISSUE TITLE
[FEATURE REQUEST] Add support for custom MOD keys when resizing via scrollwheell

### ISSUE THREAD

**Issue by SiameseParrots** [xRyul/obsidian-image-converter#47]
Most of the time  Shift + Scollwheel for page sidescrolling.
The difficulty occurs when images are stretched along the horizontal axis, so if u want to sidescroll u need to hover with the mouse over an empty canvas space.  
Can be tricky not to hit the scale-shift-scroll event when there are some images stacked. 

If its possible a toggle between Alt and Shift would be great!

**Comment by xRyul** [comment]
Added in [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0)

![image](https://github.com/user-attachments/assets/97c391cb-5eef-4eb5-bde7-49438c39cabc)
