### ISSUE TITLE
[FEATURE REQUEST] Add option to resize  EXCALIDRAW embeddings via "| size" syntax via drag-resize or scroll-wheel 

### ISSUE THREAD

**Issue by QSC707** [xRyul/obsidian-image-converter#49]
example

original
! [[Drawing 2024-01-18 13.27.33.excalidraw]]
Complete the resizing
! [[Drawing 2024-01-18 13.27.33.excalidraw|200]]

**Comment by xRyul** [comment]
Excalidraw is not an image, thus seems redundant to support such feature in this plugin. Probably better place would be to contact Zsolt himself to directly implement it in his plugin.
