### ISSUE TITLE
[Bug] This plugin should not touch PDF thumbnails

### ISSUE THREAD

**Issue by RyotaUshio** [xRyul/obsidian-image-converter#51]
Hi, thank you so much for this wonderful plugin - it lets me feel much easier when adding images to my vault because I don't have to worry about file sizes too much thanks to it!

One thing I noticed is that Image Converter also operates on PDF thumbnails, which I think is unexpected.

https://github.com/xRyul/obsidian-image-converter/assets/72342591/31add1fd-8053-4e7a-b7a4-9cd20ccd631e

**Comment by xRyul** [comment]
Good catch! Thanks for reporting! 

Fixed in [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0), now it should only work in Reading or Live preview. With optional toggle to enable/disable it in Reading Mode.
