### ISSUE TITLE
[Bug] When you paste an image into an Excalidraw file and then close the Excalidraw file, the image file will be converted to a webp file

### ISSUE THREAD

**Issue by doit132** [xRyul/obsidian-image-converter#56]
# Bug description

When you paste an image into an Excalidraw file and then close the Excalidraw file, the image file will be converted to a webp file.

However, the image file remains as a PNG file in the Excalidraw file. 
Resulting in the inability to display the image in the Excalidraw file.

# Animation demonstration

![recording](https://github.com/xRyul/obsidian-image-converter/assets/117004316/8f0bd66b-f69a-43a2-b011-927ef274f19a)

# Test Environment

- Obsidian v1.5.11
- SandBox Vault
- All other plugins have been turned off
- Windows

**Comment by xRyul** [comment]
Fixed in the latest release [1.1.2](https://github.com/xRyul/obsidian-image-converter/releases/latest) 

https://github.com/user-attachments/assets/dba739bd-8537-415f-919e-41ad50ad361a
