### ISSUE TITLE
Setting to only shrink larger images, not upscale smaller images

### ISSUE THREAD

**Issue by ZachAttakk** [xRyul/obsidian-image-converter#58]
As an example, if image resize is set to 500px (any resize setting, for instance "width"), larger images are resized down to the correct size, but **small images are upscaled to the same resolution**. When Book Search brings in a book cover (128x196px) it is scaled up to 500px to horrible effect.

Before:
![image](https://github.com/xRyul/obsidian-image-converter/assets/44269032/4355c1d6-7bf2-407b-b610-13cb216bd88e)

After:
![image](https://github.com/xRyul/obsidian-image-converter/assets/44269032/c6d8f632-115c-4a69-b595-0c8798540a9f)

This necessitates that the setting remain off and larger images needing to be scaled individually.

Is it possible to have a setting that will only scale images down if they are over the size threshold?

**Comment by xRyul** [comment]
Hey, just to confirm are we talking about non-destructive resize which uses |size at the end of the links? or destructive option which actually modifies original binary file?

Regardless, I will look into adding a toggle for both as this is not the first time I am seeing this request.

**Comment by ZachAttakk** [comment]
I was referring to **destructive** resize. When processing a note the idea is to downsize the 12 megapixel images from a phone without upscaling tiny 190px thumbnails or having to convert them one by one.

**Comment by xRyul** [comment]
Please update to the [latest release](https://github.com/xRyul/obsidian-image-converter/releases/latest) and see if the new options help 🙌
