### ISSUE TITLE
[FEATURE REQUEST] Option to skip .webp (or any other user defined  formats) when converting all images in vault 

### ISSUE THREAD

**Issue by strange-pixels** [xRyul/obsidian-image-converter#59]
First of all, I love this plugin very much. Thank you for all your hard work on it!

My feature request would be an option on the _Process all vault images_ panel to skip processing images of a certain filetype (i.e. webp images). Right now it seems to do exactly what it says (processes all images in the vault), regardless of wether or not they have already been converted. Occassionally, I like to run this command when tidying up my vault, but it would be nice if it would only process unprocessed images.

Thanks!

**Comment by strange-pixels** [comment]
Hold up, I see @KaiReichart already has a pull request submitted for this feature. Would be nice to see this implemented!  https://github.com/xRyul/obsidian-image-converter/pull/48#issue-2102523700

**Comment by xRyul** [comment]
There are some improvements in [1.2.3](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.3) for both commands: when processing whole vault or whole note. You can explicitly specify which formats to skip too. 

<img width="504" alt="image" src="https://github.com/user-attachments/assets/33ca561e-fd42-4326-b4f4-6e806255ebe2">

I am closing this for now.
