### ISSUE TITLE
FR: add a switch to auto image converter

### ISSUE THREAD

**Issue by YIRU69** [xRyul/obsidian-image-converter#6]
Hi, I have a some problem when I sync my note. The image converter plugin always auto image attachments files. It will mix the sync file like png and jpg files.
So could you add a function that it can switch to auto image converter.

**Comment by xRyul** [comment]
Fixed with [1.1.5](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.1.5)

**Comment by YIRU69** [comment]
Hi, I can't find it solved the FR on 1.1.5. I hope it can add a function can choose and decide the auto rename. On the plugin, I just only switch on or off the auto rename. I mean I need auto rename and want it can be control. For example, I paste a image and I can choose the auto rename on or off. And may be I can change it by some regular rename way.

**Comment by YIRU69** [comment]
But I really appreciate it can fix `Image Renaming: Fixed an issue where images were being renamed during sync or git pull.`

**Comment by xRyul** [comment]
For example if we have `image.jpg`

- To convert it into another format (e.g. WEBP), without compression, without any renaming: `image.jpg` -> `image.webp`  
  - Settings -> Select format to convert images to: WEBP -> Quality: 100 -> Auto rename: OFF
  The resulting file will be:  `image.webp` {converted and compressed with original name}
- If you want to have original obsidian naming structure for pasted file `image.jpg` to be renamed as `Pasted image 20231008100229.png` 
  - Simply disable the plugin. 
- If you want to **keep original image name**, and be able to **compress** it/**resize** it without converting the format: `image.jpg` -> `image.jpg`  
  - Settings -> Select format to convert images to: Same as original -> Quality: Yourdesiredcompressionvalue -> Auto rename: OFF. 
  The resulting file will be:  `image.jpg` {compressed with original name}

> ... I paste a image and I can choose the auto rename on or off. 
- If you want different option for each dropped/pasted image, then you would need to go through the settings every single time.

**Comment by YIRU69** [comment]
I greatly appreciate your patient response, which has helped me better understand how this plugin works. However, I would like to explain to you the desired outcome I have in mind, as I believe it can help avoid using different settings for various needs. I hope that when an image is pasted, a window can pop up for people to make a choice, as people's requirements are not always the same. If this can be achieved, I would both know that I need to perform an operation on the image to avoid accidental actions and have the option to choose how to handle the image differently. What do you think?

**Comment by xRyul** [comment]
Sure, if there will be interest, I will look into it. Although could you please raise a new issue for it, so i could track it please.
