### ISSUE TITLE
[BUG]: Non-destructive image resizing doesn't get applied to links on iOS 

### ISSUE THREAD

**Issue by weichselbaum** [xRyul/obsidian-image-converter#60]
Hello!

Non-destructive image resizing is not working on iOS for me. Is anyone else experiencing the same issue?

The plugin works great on my Mac. Thank you for your contribution! <3

**Comment by juanbretti** [comment]
From time to time, the non-destructive image resizing does not work for me on **Windows**.
I mean, the value is set, but the image is displayed at the original size. To properly display the image, I need to close and reopen the note.

```
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 17
		1: Text Format v3.0.2
		2: Omnivore v1.10.1
		3: Templater v2.2.3
		4: Dataview v0.5.66
		5: Calendar v1.5.10
		6: Settings Search v1.3.10
		7: Homepage v3.8.0
		8: Text Extractor v0.5.1
		9: Omnisearch v1.22.2
		10: Natural Language Dates v0.6.2
		11: Mind Map v1.1.0
		12: Excalidraw v2.1.4
		13: Git v2.24.1
		14: Tag Wrangler v0.6.1
		15: Tasks v7.0.0
		16: Plugin Update Tracker v1.5.2
		17: Image Converter v1.1.7

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by xRyul** [comment]
Please update the plugin to the [latest release](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0) and test it.

Pre [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0) version , plugin was failing to load on mobile, which consequently failed to apply  |size to the links. This should be fixed now.

Please check it out, and get back to me if you still have any issues
🚀🙌
