### ISSUE TITLE
[Bug] Added images not converted on Obsidian Android

### ISSUE THREAD

**Issue by Pil0tXia** [xRyul/obsidian-image-converter#62]
### How to reproduce

Add an image file by paperclip icon.

![3c8b6b77c3296b4c9de6a47d79c0c861](https://github.com/xRyul/obsidian-image-converter/assets/41445332/d5e66d55-bb8c-4cfd-a679-de4bb3043d5c)

### What's expected

The image should be converted to `webp`, instead of remaining `png`.

### Version

Obsidian v1.5.12

![Screenshot_2024-05-24-01-57-14-005_md obsidian](https://github.com/xRyul/obsidian-image-converter/assets/41445332/c9f504dd-23c7-4bca-9394-e3fdcd9106f0)

Hope that it can be fixed, thanks!

**Comment by Clover-Zero** [comment]
I think this happens because the images aren't "dragged and dropped/pasted", and this plugin can only do that. Happens to me too. I do wish it works on Android, too.

**Comment by bav2653** [comment]
This problem still hasn't been fixed. The addon is very useful, but I add most files to Obsidian via the Android version.

**Comment by xRyul** [comment]
I dont have Andorid device to test it, however on iOS this should be fixed. Plugin was failing to load some libraries which were responsible for decoding HEIC images, which in essence blocked all processing. Now it should be fixed. 

If it still doesn't work please get back 🚀 🙌

**Comment by bav2653** [comment]
> I dont have Andorid device to test it, however on iOS this should be fixed on [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0). Plugin was failing to load some libraries which were responsible for decoding HEIC images, which in essence blocked all processing. Now it should be fixed.
> 
> If it still doesn't work please get back 🚀 🙌

The addon works correctly. Thank you very much for your work!

**Comment by xRyul** [comment]
Awesome, I will close this for now
