### ISSUE TITLE
cursor moves to the beginning ! after pasting the images.

### ISSUE THREAD

**Issue by orvpagadua** [xRyul/obsidian-image-converter#65]
cursor moves to the beginning ! after pasting the images. this drives me crazy

**Comment by juanbretti** [comment]
This feature request is similar to #34 .

**Comment by xRyul** [comment]
Please test it in [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0)  It adds new option to set cursor position either at the front or back of the link.

![image](https://github.com/user-attachments/assets/8a88662b-26f3-4f52-ac43-3d27f05ebb23)

This setting works on pasted and dropped images, during resizing via dragging edge of the image and via scrollwheel. Although this settings wont do anything if you e.g.: click on the image. 

If something is broken, or missing please get back to me
 🚀🙌
