### ISSUE TITLE
Plugin does not convert the image file attachments of a note

### ISSUE THREAD

**Issue by merlinuwe** [xRyul/obsidian-image-converter#68]
For me, it does not work anymore with Obsidian 1.6.7. Not with opened note and not with the folder attachments selected. I have png files.

Windows 10
Android 11

**Comment by xRyul** [comment]
Please update to the [latest](https://github.com/xRyul/obsidian-image-converter/releases/latest) version. And let me know if conversion still doesn't work. 

Were you using image format as the target format? e.g. simply trying to compress pngs? or also trying to convert it into another format? Trying to process all vault or all images in 1 note?

**Comment by merlinuwe** [comment]
Thanks for your investigation. It seems to work with png, webp and jpg as source and webp as the target. I tried to process one image in a note at a time. I'll test more in the next days.

Is it possible to rename the image when dragging it from the webbrowser to the note? (The activated image rename plugin ignores your plugin, sadly.)

**Comment by xRyul** [comment]
Dragging from the browser? yes. Copy pasting from the browser? yes. Renaming? yes. You can even setup dropped/pasted images to use markdown links separately from default Obsidian wiki links. 

https://github.com/user-attachments/assets/913b3c5f-7c84-47b8-a4eb-a693d4810e40

Sorry, I am not sure what do you mean by "activated image rename plugin" 🥲
