### ISSUE TITLE
[Feature Request]: Ignore certain formats from processing (to avoid reprocessing)

### ISSUE THREAD

**Issue by nosthans** [xRyul/obsidian-image-converter#69]
### [Feature Request]: Ignore certain formats (to avoid reprocessing)

Currently, running operations to processing the images twice appears to reapply the compression to all the target files.
By having the ignored formats filter(eg: webP), one could bath run the image optimization without recompressing the already processed files.

Usecase
I often copy many snippets from webpages (about a 100 in a given week), then use another addon to download the linked image to the local directory (generally as jpg/png). As there are many notes with unoptimized files, running Image Converter against each note is not very realistic in my day to day operation.

1. Webpage snippets added to Obsidian
2. Linked images downloaded to local folder and note links updated
3. Image Converter run to save space against the vault; linked images compressed and links updated
5. More webpage snippets added, downloaded locally
6. Image Converter ran against the vault
7. The images that have already been processed in step 3 gets recompressed

I'd like for the ability to filter out certain extensions from being processed so there would not be unneeded processing/quality loss.

**Comment by nosthans** [comment]
After having a more careful look around, this seems to be a duplicate of issue #59 and the PR #48 seems to address this.
Please consider merging the PR.

**Comment by xRyul** [comment]
I have merged the PR, however I need some more testing. For now I will close this, please continue in https://github.com/xRyul/obsidian-image-converter/issues/59
