### ISSUE TITLE
[FEATURE REQUEST]: Converting, compressing and resizing all existing images in vault

### ISSUE THREAD

**Issue by materemias** [xRyul/obsidian-image-converter#7]
Could you add a functionality to do that?

**Comment by xRyul** [comment]
hey, thanks for checking out the plugin. I will look into it. 

Although, if you have a lot of images to process at once: e.g: 500+ spread out across multiple formats (psd, tif, jpg, jpeg, heic, gif etc.) I would better use something like "XnConvert", as it will be able to use all available cores and will be much faster.

**Comment by xRyul** [comment]
Will try to release it in the next couple of days:
- Ability to convert, compress and resize all internal images in **current note**

  ![image](https://github.com/xRyul/obsidian-image-converter/assets/47340038/71a65249-9e94-4da5-baac-d3de9c6ce48c)

  ![image](https://github.com/xRyul/obsidian-image-converter/assets/47340038/94c68b5b-084f-497d-b575-6a9b594d6461)

- Ability to convert, compress and resize images across **all Vault**


A few things to consider:
- This does not download **_externally embedded images_**. 
- Currently, for safety reasons, it does not support selecting the Output location. 


https://github.com/xRyul/obsidian-image-converter/assets/47340038/53d81316-e5d3-4669-8c4f-8bed03dd924f

**Comment by tylerjames** [comment]
Just tried this **Process all vault image** feature and it worked great and was pretty quick (my vault is not huge)

It definitely made my canvases much snappier when scrolling. Well done

**Comment by Sinled** [comment]
Hi, is there any means to spead up conversion? I was trying to convert images (on m1 max mac) in a whole vault but it will take several months to convert ~6k images )

I see somewhere between 180 to 200 second for 1 image conversion, but when i am using cwebp converter with similar settions it takes 1-2 seconds per image
