### ISSUE TITLE
[FEATURE REQUEST] Temporarily disable image conversion on drop/paste

### ISSUE THREAD

**Issue by esamecar** [xRyul/obsidian-image-converter#72]
I'm not quite sure how it could best be implemented, but I would like to be able to temporarily switch off the automatic conversion for individual images that I add via drag & drop. Possibly simply via an Obsidian command, e.g. "Disable next Image Resizing". 

Why do I want this? In 99% of the cases I use quite small images, but sometimes I need the full quality to be able to extract certain information from the images. Right now I manually disable the plugin, import the picture and reenable it.

**Comment by xRyul** [comment]
Please test it with [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0) It adds new command to  temporarily pause/continue the conversion. 

![image](https://github.com/user-attachments/assets/f5a127e8-28a0-4ef3-8655-80ca7ae0ef3b)

If something is broken, or missing please get back to me
 🚀🙌

**Comment by jack2game** [comment]
I think this function was removed from the recent version? Is it still possible to achieve this?
