### ISSUE TITLE
[FEATURE REQUEST] custom rename

### ISSUE THREAD

**Issue by zippermonkey** [xRyul/obsidian-image-converter#74]
Is there a plan to support custom rename?

**Comment by xRyul** [comment]
Yes, but it is not released yet, you will be able to build custom Filenaming and Folder creation structures using variables, including but not limited to:


> '{imageName} - Original file name',
> '{noteName} - Active note name',
> 
> '{date:YYYY-MM-DD} - Full moment.js support',
> 
> '{pathDepth}',
> '{directory} - to be removed',
> '{parentFolder} - to be removed',
> '{folderName} - current folder name',
> 
> '{currentDate} - todays date in YYYY-MM-DD',
> '{yyyy} - year e.g. 2024',
> '{mm} - month e.g.: 12',
> '{dd} - day e.g.: 24',
> '{time} - 24h format e.g.',
> '{HH} - hour',
> '{timestamp}',
> '{weekday} - e.g.: Monday, Tuesday, Wednesday',
> '{month} - e.g.: October, September, December',
> '{calendar} - e.g. Today at 9_25 PM',
> '{creationDate} - creation date',
> 
> '{platform} - e.g. win32',
> '{userAgent}',
> 
> {MD5:imageName:X} - MD5 hashed value X values long e.g.: {MG5:imageName:8} 
> '{counter:000} - Incremental counter with padding',
> '{uuid} - Random UUID',
> '{random} - rnadom string of characters e.g. 91c2q1, 09a5xb',
> '{randomHex: X} - generate random HEX string X values long',
> 
> '{width} - Image width',
> '{height} - Image height',
> '{resolution} - Image resolution e.g. 1980x1980',
> '{quality} - Conversion quality',
> '{fileType} - Image filetype e.g. jpg, png , tif, webp, bmp etc.',
> 
> '{size:MB:2} - MB, KB, B - digits specifies decimal value',
> '{sizeMB} - File size in MB',
> '{sizeB}',
> '{sizeKB}',
> '{ratio} - image ratio',
> '{orientation} - e.g. portrait or landscape',



![image](https://github.com/user-attachments/assets/755b9fca-c8f3-4a75-afc7-ce5f418a487a)


Is there any format specifically you would want?

**Comment by zippermonkey** [comment]
> Yes, but it is not released yet, you will be able to build custom Filenaming and Folder creation structures using variables, including but not limited to:
> 
> > '{imageName} - Original file name',
> > '{noteName} - Active note name',
> > '{date:YYYY-MM-DD} - Full moment.js support',
> > '{pathDepth}',
> > '{directory} - to be removed',
> > '{parentFolder} - to be removed',
> > '{folderName} - current folder name',
> > '{currentDate} - todays date in YYYY-MM-DD',
> > '{yyyy} - year e.g. 2024',
> > '{mm} - month e.g.: 12',
> > '{dd} - day e.g.: 24',
> > '{time} - 24h format e.g.',
> > '{HH} - hour',
> > '{timestamp}',
> > '{weekday} - e.g.: Monday, Tuesday, Wednesday',
> > '{month} - e.g.: October, September, December',
> > '{calendar} - e.g. Today at 9_25 PM',
> > '{creationDate} - creation date',
> > '{platform} - e.g. win32',
> > '{userAgent}',
> > {MD5:imageName:X} - MD5 hashed value X values long e.g.: {MG5:imageName:8}
> > '{counter:000} - Incremental counter with padding',
> > '{uuid} - Random UUID',
> > '{random} - rnadom string of characters e.g. 91c2q1, 09a5xb',
> > '{randomHex: X} - generate random HEX string X values long',
> > '{width} - Image width',
> > '{height} - Image height',
> > '{resolution} - Image resolution e.g. 1980x1980',
> > '{quality} - Conversion quality',
> > '{fileType} - Image filetype e.g. jpg, png , tif, webp, bmp etc.',
> > '{size:MB:2} - MB, KB, B - digits specifies decimal value',
> > '{sizeMB} - File size in MB',
> > '{sizeB}',
> > '{sizeKB}',
> > '{ratio} - image ratio',
> > '{orientation} - e.g. portrait or landscape',
> 
> ![image](https://private-user-images.githubusercontent.com/47340038/380709402-755b9fca-c8f3-4a75-afc7-ce5f418a487a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTM3NDYsIm5iZiI6MTczMDE5MzQ0NiwicGF0aCI6Ii80NzM0MDAzOC8zODA3MDk0MDItNzU1YjlmY2EtYzhmMy00YTc1LWFmYzctY2U1ZjQxOGE0ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA5MTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxYTY4YzhhOTUxOGUxMDg2NGYxY2Q3NmE3MzEwNTI2NGJmOTQ4MDQ2OWQ4MDVjNzJjNzYzYWY4OWU4NjI2YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8k6Ulz1PD-uLXv24xAfAfydRfCdgYl84i92kqZG1J2I)
> 
> Is there any format specifically you would want?

Awesome! For me, it totally enough!

**Comment by xRyul** [comment]
Please test it with [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0), if something is missing or is broken, please get back to me 🚀🙌
