### ISSUE TITLE
Project conflict and “main.js” does not exist

### ISSUE THREAD

**Issue by Pagas15** [xRyul/obsidian-image-converter#75]
"How to install
1.  Downlaod main.js, styles.css, manifest.json files from this repo."

styles.css, manifest.json exist. 
But there is no “main.js” in the project.
only “main.ts”.

Please fix or instructions. And write that it is necessary to download the whole project, install dependencies, build the project. get the three files and then follow your instructions. 

Or add “main.js” file to the project. Or ideally for people who are not strong in programming. Just 1 folder where all 3 files will be stored in one place instead of searching all over the repository.

Thanks

**Comment by xRyul** [comment]
hey, I am always open to PRs if you found a mistake feel free to open one ;> Docs are indeed outdated, the only way to install it is via Obsidian, or if you want to do it manually -> main.js and manifest for the [Latest Release](https://github.com/xRyul/obsidian-image-converter/releases)
