### ISSUE TITLE
macOS fails to install image converter

### ISSUE THREAD

**Issue by reply2za** [xRyul/obsidian-image-converter#77]
First the update failed, so I tried to delete and re-install it from Community Plugins. Now I can't install it from Community Plugins either. 

System: `M-Series macbook`
OS: `15.1`

**Comment by minggangli1030** [comment]
same here

**Comment by amarseillan** [comment]
Same here, can't install through obsidian or by following the readme.
Readme says main.js which I think needs to be re-worded to main.ts ? 

Thanks

**Comment by MattFaz** [comment]
I did the same thing, to get it working again just follow the install instructions and use the `main.js` and `manifest.json` files from the last release: https://github.com/xRyul/obsidian-image-converter/releases/tag/1.1.7

**Comment by minggangli1030** [comment]
> I did the same thing, to get it working again just follow the install instructions and use the `main.js` and `manifest.json` files from the last release: https://github.com/xRyul/obsidian-image-converter/releases/tag/1.1.7

it worked, thanks

**Comment by xRyul** [comment]
Sorry for all of this! It should be fixed now (although Obsidian restart might be needed). I might have updated and pushed manifest.json file too quickly, completely forgetting that obsidian also pulls it from the main repo and not only final release 😭  
The latest version should show 1.1.7 in Obsidian.

New release is still in development and not ready. I will be introducing some new ways how we can handle folder creation and file naming, reducing overall plugin load time, as well as fixing some major bugs (e.g. Mobile support: Plugin not converting images on mobile or not applying custom sizing) - and I am currently still heavily testing it.
