### ISSUE TITLE
[BUG] iOS: Converting into WEBP via attachment results in larger files, but pasting is fine.

### ISSUE THREAD

**Issue by xRyul** [xRyul/obsidian-image-converter#78]

**Comment by ckdanny** [comment]
I hit this as well. the original size in album was 1.2 MB but it results in 9.3 MB. 
Seems this happen in mobile side. Desktop seems work fine.

**Comment by xRyul** [comment]
Closing this for now. 

New toggle in [1.2.3](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.3) allows files to be at bay.  https://github.com/xRyul/obsidian-image-converter/issues/83#issuecomment-2466454350
