### ISSUE TITLE
Bug: renaming of multiple images appends suffix the wrong way

### ISSUE THREAD

**Issue by chrisgrieser** [xRyul/obsidian-image-converter#81]
Given this setting:
![Pasted image 2024-11-05 at 14 03 23](https://github.com/user-attachments/assets/d1f6a179-4edc-4095-8c3c-69da7ac48959)

Current result when pasting 4 images:
```md
![[Lorem Ipsum_image.webp]]
![[Lorem Ipsum_image-1.webp]]
![[Lorem Ipsum_image-1-2.webp]]
![[Lorem Ipsum_image-1-2-3.webp]]
```

expected result:
```md
![[Lorem Ipsum_image-1.webp]]
![[Lorem Ipsum_image-2.webp]]
![[Lorem Ipsum_image-3.webp]]
![[Lorem Ipsum_image-4.webp]]
```

**Comment by xRyul** [comment]
[1.2.2](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.2) should handle it now as expected.

Thanks for reporting ❤️

**Comment by chrisgrieser** [comment]
Thanks for the quick fix!
