### ISSUE TITLE
[FEATURE REQUEST] Option to not convert images & ignore pattern

### ISSUE THREAD

**Issue by luisfos** [xRyul/obsidian-image-converter#89]
I would like to use only the resize functionality, but there isn't a way to disable the conversion

to go further you could have an `ignore pattern` for any images you don't want to convert, such as

- ignore all images: "*"
- ignore all avif images: "*.avif"
- ignore all cat images: "*cat*"

etc

**Comment by xRyul** [comment]
Hey, many thanks for checking out the plugin.

Are you referring to destructive or non-destructive resizing? Single image conversion, all images in 1 note, or whole vault?

To disable conversion and only use resize: 
- Convert to: "Same as original"
- Quality: 100
- Resize: pick any resize method you want.

For skipping format - currently it is only available when processing whole vault or note. If you wanna skip conversion on certain single image -> pause the conversion temporarily via CMD+P -> Toggle image Conversion (Pause/Resume))

**Comment by muratagawa** [comment]
> * ignore all avif images: "*.avif"

I would like this feature too.
AVIF images are almost always smaller in file size than WebP. So there is no point in converting them.

**Comment by muratagawa** [comment]
I'm using this 👇
https://squoosh.app/

**Comment by TonyAtlas** [comment]
Also need this feature.

In my case, I often insert images that are already of optimal quality for me and I only need the renaming function.

Perhaps it can be implemented as an option not to convert the image if it is in the same format that is specified in the plugin settings for conversion.

**Comment by xRyul** [comment]
> Besides, perhaps consider adding a command to "**Disable/Enable Image Conversion function**"? 🤔
> 
> I understand that this plugin is primarily _designed for image conversion_, which is its main feature. 
> 
> However, there are times when we want to paste images into the repository _without any loss_, ensuring they are not compressed. 
> 
> 
> 
> In such scenarios, having a command to **temporarily disable the conversion feature** would be much more convenient than switching the plugin's activation status. 

It is there, just under slightly different name "Pause/Continue"

**Comment by Moyf** [comment]
> > Besides, perhaps consider adding a command to "**Disable/Enable Image Conversion function**"? 🤔
> > I understand that this plugin is primarily _designed for image conversion_, which is its main feature.
> > However, there are times when we want to paste images into the repository _without any loss_, ensuring they are not compressed.
> > In such scenarios, having a command to **temporarily disable the conversion feature** would be much more convenient than switching the plugin's activation status.
> 
> It is there, just under slightly different name "Pause/Continue"

Oh! I see, thank you!! 🥳

**Comment by xRyul** [comment]
Glob and regex patterns will be available in 1.2.15~ 

![image](https://github.com/user-attachments/assets/2c067e91-a8d0-40b3-b21e-d1328d04c041)
