### ISSUE TITLE
Is Image Resizing meant to save the size of the image?

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [xRyul/obsidian-image-converter#9]
Per title. Have just installed and playing around but I noticed that the resizes are only temporary and are not saving the resize anywhere. Leaving the note and coming back in resets the image. Is that intended?

**Comment by xRyul** [comment]
Which option do you use to resize an image?

e.g.:

Any option from the dropdown will resize your local image file. 
<img width="320" alt="image" src="https://github.com/xRyul/obsidian-image-converter/assets/47340038/ddc6c7f2-35c1-4b49-9348-2b2e104d8048">



Below 2 options simply use Obsidian syntax to resize an image. So if you gonna try to resize image by dragging an edge of an image in Reading Mode, then it won't preserve it. 
<img width="322" alt="image" src="https://github.com/xRyul/obsidian-image-converter/assets/47340038/6d080b01-912b-45dd-a5f3-b2dfaa50db6b">

**Comment by ObsidianTTRPGProject** [comment]
That explains it. I don't use Live Preview mode and thus in Preview Mode this does not preserve the change.

**Comment by xRyul** [comment]
Thanks for testing it out nevertheless. Might gonna have to disable it for Reading Mode, just to prevent the confusion.
