### ISSUE TITLE
Broke image link in Excalidraw

### ISSUE THREAD

**Issue by YeHang-GitHub** [xRyul/obsidian-image-converter#90]
This plugin will broke image link in excalidraw when you drag and drop a image file from windows file explorer to excalidraw canvas.
File will just import in Vault root, and the image has been imported excalidraw will be link to local computer, not attachment folder. But when I disable this plugin, every thing works fine again.

**Comment by xRyul** [comment]
Hey, 

https://github.com/user-attachments/assets/0bd1fbe3-9f3d-46a4-9658-aa85369a260b

I cant reproduce it. 

Does the issue still happen when tested on sandbox vault with default settings of Excalidraw and Image Converter?

**Comment by YeHang-GitHub** [comment]
Hi, here is the step:

When both plugins are on:
1. Drag image into Excalidraw canvas, **Try not switch page after you import image, seems like this will fix it some how**
2. Hold Ctrl and click on the image, this should open this image in a new page. but instead it say File does not exist. 

When image converter off:
1. same as before, and when you drag you can see this(didn't have this when image converter are on, I guess this plugin is changing some import behavior?):
![图片](https://github.com/user-attachments/assets/0cdd1af7-fd75-42ba-89df-ff870024b988)
2. Hold Ctrl and click, it can open the image without issue.
If you have more question, I can record a video for you. 
Thank you look into this issue.I love this plugin a lot^-^

**Comment by xRyul** [comment]
Excalidraw struggles to update its cache fast enough. If you wait another 1-2 seconds, it then renders fine.

If you check the folder where image gets saved to -> image appears there and gets saved + renamed immediately. But at the same time, even after conversion when CMD+Clicking on the image inside Excalidraw - it still struggles to find it. 

It registers the original image, but doesn't register it after conversion fast enough. Hence the discrepancy. If you use Excalidraw, I would suggest to simply Pause the conversion entirely: CMD+P -> Pause image converter -> Then when you are back in MD note, you can simply run the same command again to re-enable conversion. 

ZSolt added custom event listeners to his plugin. I sadly don't have enough time to track all his custom mods. Especially, that I don't use Excalidraw myself, so support will be very limited. If anyone would like to extend Image Converter to better support Excalidraw the code is open source and PRs are more than welcome.
