### ISSUE TITLE
SVG: Renaming always changes the file extension

### ISSUE THREAD

**Issue by HypedLama** [xRyul/obsidian-image-converter#91]
When I disable "allow larger Files after conversion" and insert a svg for example. The svg will not be converted but the name will be changed from oldname.**svg** to newname.**png** or webp/jpg but the image will no longer be displayed in obsidian because you cannot open a svg as png/webp/jpg

One example svg: https://www.svgrepo.com/svg/535115/alien

Steps to recreate:
disable allow larger Files after conversion
enable some rename rule
drag svg into obsidian
file gets renamed to png/webp/jpg and can no longer be displayed by obsidian

**Comment by xRyul** [comment]
SVG is not supported by this plugin. While you might get lucky and certain files will get parsed and converted, it might not work on others.

SVG requires different conversion and parsing techniques of what this plugin currently does. 

SVG is vector image, while plugin is meant for raster images.

**Comment by HypedLama** [comment]
But why does it convert svg files then and also renames them ?
Why are files renamed the file extension specifically if they are not converted ?

**Comment by HypedLama** [comment]
Gif demonstrating the problem:
![fileextensionchanged](https://github.com/user-attachments/assets/4fe5b41b-4fb9-4457-b9fd-c94ab5e863f5)

**Comment by xRyul** [comment]
No renaming example = renders fine
![Obsidian_n4tRGEpBhc](https://github.com/user-attachments/assets/d78dfe62-e247-4da5-869e-41b97306219d)

With renaming = renders fine
![Obsidian_7gPtSvtchX](https://github.com/user-attachments/assets/15d0c3f4-f017-429d-8b8c-fdcbbbb358b5)

As mentioned earlier, if you want to convert to another format, then you are on your own, it might work, it might not. Sorry I rarely use SVGs myself, and is in a low priority right now. I am the only dev of this plugin, working on it only in my free time. If you really need SVG and enjoy the development so far please consider supporting it via ko-fi link.

**Comment by HypedLama** [comment]
Mh I have finals and have never worked with obsidian plugins but I might be able to do a PR where file extensions don't get changed if the file is not converted.
