### ISSUE TITLE
Update from 1.2.6 -> 1.2.7 does not work

### ISSUE THREAD

**Issue by merlinuwe** [xRyul/obsidian-image-converter#92]
Win 10

![image](https://github.com/user-attachments/assets/fd43fae8-d971-46b9-b07a-87378b4c6835)

![image](https://github.com/user-attachments/assets/c00ca376-a8cc-4b1c-b2e5-a8c72bc4221d)

**Comment by xRyul** [comment]
You are too quick 😅
