### ISSUE TITLE
Unable to locate image file

### ISSUE THREAD

**Issue by TonyAtlas** [xRyul/obsidian-image-converter#93]
When I choose "Annotate image", it says "Unable to locate image file". I tried with adifferent images, but its all the same.

Win 10 / Obsidian 1.7.7

**Comment by xRyul** [comment]
Does the same happen on sandbox vault?  Can you show me your installed plugins and also the src path of an image e.g.: CMD+SHIFT+I -> Use inspector tool to click on the image in the note -> then copy/paste the path of src here e.g.:

src="app://9aecf3550a86937a59fcfcf544bd3fd83ae1/C:/Users/Username/Desktop/path/path/path/attachments/B%C3%A4ume-6.webp?1732047380245"

**Comment by TonyAtlas** [comment]
> This might happen when image didn't have time to e.g. get converted properly. In particular with HEIC, TIFF or PNG images. They all takes extra long to process. Which might lead to this error. When error appears, try switching to another note and then back, does the image link appear fine, or is it broken?
> 
> If above is not the issue, does the same happen on sandbox vault? Can you show me your installed plugins and also the src path of an image e.g.: CMD+SHIFT+I -> Use inspector tool to click on the image in the note -> then copy/paste the path of src here e.g.:
> 
> src="app://9aecf3550a86937a59fcfcf544bd3fd83ae1/C:/Users/Username/Desktop/path/path/path/attachments/B%C3%A4ume-6.webp?1732047380245"

I tried “Annotate image” on images that have been in my storage for a long time and they didn't require conversion to another format. I only have jpg files.

I have disabled all plugins except yours and the error still appears. But in another vault "Annotate image" works.

Example src path of an image on which “Annotate image” does not work:

src="app://eade502259c1462987f1b8cac81eb0b7f97c/C:/Doc/Tony%20Atlas/Pasted%20image%2020241118143729.jpg?1731929850534">

For experiment I put the image in the root of the vault and tried "Annotate image" from there. But that didn't work either.

**Comment by xRyul** [comment]
Could you please send me an example jpg you are working with?

**Comment by TonyAtlas** [comment]
> Could you please send me an example jpg you are working with?

Yes, of course. Here's one of many examples:

![Pic_20230216_232434](https://github.com/user-attachments/assets/30961ca4-2b23-4a6f-96c0-5ca1beb90c62)

**Comment by TonyAtlas** [comment]
I think I've discovered the problem.
In a vault whose name consists of one word the plugin works fine. But if the storage name consists of two or more words, this error appears.

Please try to reproduce it for yourself.

**Comment by TonyAtlas** [comment]
After the awesome 1.2.8 update, this bug has been fixed.
Thank you so much for the fix and such awesome functionality. The plugin has become much more useful for me. 🙏
