### ISSUE TITLE
Annotated images (version 1.2.7) are always in PNG?

### ISSUE THREAD

**Issue by juanbretti** [xRyul/obsidian-image-converter#94]
Hello,
Quick question.

When annotating an image, is the file always saved as PNG?
Even when the original was JPEG, and the actual filename has extension .jpg
I do understand you are trying to preserve transparency. That's why you are using PNG?

Thank you! Great idea to have a quick annotation tool!

![image](https://github.com/user-attachments/assets/e117a1f3-7f1b-473d-a18d-52dcff126f28)

```log
SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: Windows 11 Pro 10.0.22631
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 18
	Plugins enabled: 18
		1: Text Format v3.1.0
		2: Templater v2.9.1
		3: Dataview v0.5.67
		4: Calendar v1.5.10
		5: Settings Search v1.3.10
		6: Homepage v4.0.7
		7: Text Extractor v0.5.2
		8: Omnisearch v1.25.1
		9: Natural Language Dates v0.6.2
		10: Excalidraw v2.6.7
		11: Git v2.28.2
		12: Tag Wrangler v0.6.1
		13: Tasks v7.13.0
		14: Enhancing Export v1.10.9
		15: CSV Codeblock v1.1.0
		16: Mind Map v1.1.0
		17: Plugin Update Tracker v1.6.0
		18: Image Converter v1.2.7
```

**Comment by xRyul** [comment]
Another option is to have WEBP embedded into formats which do not offer transparency. This technically would lower the file size too. However, it might break previews and thumbnails on some setups. Thus, PNG was the safest. 

Or embed PNG into PNG, WEBP into WEBP etc. and then JPG/JPEG would have white or black background. But this makes it much harder to deal with different color schemes e.g.: when flattening. Thus again, in this case PNG is simply more universal too. 

If you would like to play around with it:
- [main-webp.zip](https://github.com/user-attachments/files/17821617/main-webp.zip) - this will embed webp, and provide slightly lower file sizes, but might break previews etc.
- [main-preserve_original.zip](https://github.com/user-attachments/files/17821636/main-preserve_original.zip) - if it is jpg, jpeg, gif then it will flatten it, if png it will embed png, if webp then embed webp

**Comment by juanbretti** [comment]
@xRyul , you have very good points. I agree with you that PNG is the safest way to keep transparency.
For that scenario, maybe I would recommend renaming the file extension to `.png`, so it is clear for the user.

Another solution could be to add a feature to remove transparency (set a solid background).
You might need to consider settings for:
* Remove transparency
* Saving format for the composite image (`.jpg`, `.webp`, `.png`, same as original, same as "Convert > Convert to",...)
* Define a default background color.
   * Maybe you could copy the note background color from Obsidian as default

By the way, this *annotations* is a very cool feature for this plugin.

**Comment by xRyul** [comment]
I've added some custom backgrounds in the latest release.  User can select one of a few custom backgrounds. Thus if user opens JPG,  which doesn't support transparency by default, transparency wont be preserved, and if user doesn't like default flattened black background they can switch to e.g. white. I might add some more custom backgrounds , might not. 

Also - PNG wont be default embeddable format anymore, instead it will use  format of the original file. So if file format doesn't allow transparency, then it won't force it. Having transparency in JPGS is very system dependant, thus it was causing some confusion with some users, and produced black images. 

Exporting to custom formats wont happen anytime soon. Unless someone would like to create a PR.

**Comment by juanbretti** [comment]
@xRyul , I saw it yesterday. Terrific addition to the plugin.

The only thing for you to consider, is:
- The original image is called `pepe.jpg`
- The user requests a transparent background, selecting from your cool-new options
- The image gets stored in `PNG`
- But the file name does not get renamed as `pepe.png`. It is still named `pepe.jpg` while inside the file is a Portable Network Graphics.

Thank you again for this great feature and all the hard work.
