### ISSUE TITLE
[BUG] annotation on vertical images: webp image content missing on save 

### ISSUE THREAD

**Issue by yanqing-song** [xRyul/obsidian-image-converter#96]
Simple image annotation is the feature I need most in Obsidian. Many thanks!

All my images are .png screenshots converted to .webp using the plugin. Annotations on horizontal images are perfect. But with vertical images, after I added an arrow and saved the image, the original image was gone, leaving only the arrow. 

Horizontal image, before:
![Untitled-20241119202431](https://github.com/user-attachments/assets/d0c29eb7-7e82-46a2-80df-b70bff2ed965)

Horizontal image, after: 
![Untitled-20241119202431 2](https://github.com/user-attachments/assets/f430c838-84bb-4ebd-963b-7ee0100f6ae4)

Vertical image, before:
![Untitled-20241119202406](https://github.com/user-attachments/assets/7a6ac999-b534-4cb9-8a3b-1f48ca0710c6)

Vertical image, after:
![Untitled-20241119202406 2](https://github.com/user-attachments/assets/11309535-df88-46aa-af5b-eb80c83358ce)

**Comment by xRyul** [comment]
I am looking into this. And it is such a strange bug. If I open Developer tools to see the console. Then it works fine, but as soon as i close it, the bug comes back.

**Comment by xRyul** [comment]
I've fixed it, but will hold for a little for further testing before releasing 🥲


https://github.com/user-attachments/assets/8d005737-ad69-40a6-8e3f-a767ebe2aeb0

**Comment by purrrfecto** [comment]
antivirus got absolutely crazy when I try to download the zip file. By any chance you can isolate the main.js to a branch or gist or whatever?

**Comment by yanqing-song** [comment]
> I think I've fixed it, but will hold for a little for further testing before releasing 🥲 if you would like to see if it works, you can try replacing main.js inside /image-converter folder with this updated version: [main.zip](https://github.com/user-attachments/files/17822968/main.zip)
> 
>  Obsidian_Bhqzj9nxVi.mp4

The updated version works for me. All look good now 👍
