### ISSUE TITLE
[BUG] Scrolling doesn't work on pictures on Android

### ISSUE THREAD

**Issue by kinzad** [xRyul/obsidian-image-converter#97]
When I'm trying to scroll note while holding finger on picture it doesn't work. 

https://github.com/user-attachments/assets/1e66e845-d695-45d7-a621-35a4dddee2f4

I suppose it's because of drag resize function, but turning it on/off doesn't help.

**Comment by xRyul** [comment]
Was able to reproduce and it is already fixed 65b21c022cf087038a0e085237a2d99f6106973b Will be available in the next update.
