### ISSUE TITLE
[BUG] Image resizing with drag and drop stopped working.

### ISSUE THREAD

**Issue by Friedolito** [xRyul/obsidian-image-converter#98]
It is still possible to resize the image temporarily. 
But no size is added to the image link, and when reloading the page, the image will be in its original size. 

Can’t pinpoint the exact time when this started, but it could have happened with the last Obsmd update. 

Plug-In: Version: 1.2.8
Obsmd: V1.7.7

![Screenshot -2024-11-21 at 13 50 14](https://github.com/user-attachments/assets/c29869e9-2a47-4f4e-af61-63b397c08803)

**Comment by xRyul** [comment]
I am on the latest version too, but currently unable to replicate 😭

A few things to try out:

a) Does the same happen whem resizing with scrollwheel? 
a) Does the same happen after reinstalling the plugin?
b) Does the same happen on sandbox /clean vault?
c) Try switch cursor position:  front / back
<img width="601" alt="image" src="https://github.com/user-attachments/assets/b9d11aa5-a884-4260-a977-892ceb0150bf">


Also what are those icons next to the image?

**Comment by xRyul** [comment]
Unable to replicate. Closing it for now. Please comment back if issue still persists after you have tried all the steps mentioned earlier.
